#version 460
#pragma shader_stage(compute)

#extension GL_EXT_debug_printf : enable
#extension GL_EXT_nonuniform_qualifier: enable
#extension GL_EXT_buffer_reference: require
#extension GL_EXT_scalar_block_layout: enable

#include "../SharedStructs.h"

layout (push_constant) uniform PushConstants {
    PushConstantsData pushConstants;
};

#include "../Bindings.glsl"
#include "../Common.glsl"
#include "../PathTracing/Intersection.glsl"
#include "../PathTracing/PrimaryRayGen.glsl"

layout (local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;
void main() {
    const ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 screenSize = imageSize(outputColor);
    primaryRayGen(pixelCoord, screenSize);
}
