#version 460
#pragma shader_stage(compute)

#extension GL_EXT_debug_printf : enable
#extension GL_EXT_nonuniform_qualifier: enable
#extension GL_EXT_buffer_reference: require
#extension GL_EXT_scalar_block_layout: enable

#include "PathTracerEntryShared.glsl"
#include "../PathTracing/IntersectionDirect.glsl"
#include "../PathTracing/PrimaryRayGenDirect.glsl"

void main() {
    const ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 screenSize = imageSize(outputColor);
    primaryRayGenDirect(pixelCoord, screenSize);
}
