#version 460

#include "../SharedStructs.h"

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

layout(binding = 0, rgba32f) readonly uniform image2D inputImage;
layout(binding = 1, rgba8) writeonly uniform image2D outputImage;

// Column-major matrices for GLSL
const mat3 ACESInputMat = mat3(
0.59719, 0.07600, 0.02840,
0.35458, 0.90834, 0.13383,
0.04823, 0.01566, 0.83777
);

const mat3 ACESOutputMat = mat3(
1.60475, -0.10208, -0.00327,
-0.53108,  1.10813, -0.07276,
-0.07367, -0.00605,  1.07602
);

vec3 RRTAndODTFit(vec3 v) {
    vec3 a = v * (v + 0.0245786) - 0.000090537;
    vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081;
    return a / b;
}

vec3 ACESFitted(vec3 color) {
    color = ACESInputMat * color;       // Apply ACES input matrix
    color = RRTAndODTFit(color);        // Apply RRT + ODT fit
    color = ACESOutputMat * color;      // Apply ACES output matrix
    return clamp(color, 0.0, 1.0);      // Clamp to [0,1]
}

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    vec4 hdrImage = imageLoad(inputImage, pixel);
    imageStore(outputImage, pixel, vec4(ACESFitted(hdrImage.rgb), hdrImage.a));
}